        @media(max-width:1100px){.report-grid{grid-template-columns:1fr 1fr;grid-template-areas:"summary summary" "gauge pillar" "tpb tpb" "priority priority" "featured featured" "regions regions"}.report-tpb-card .report-chart{height:230px}.report-regions-content{min-height:300px}.report-header{grid-template-columns:160px 1fr 130px}.report-title{font-size:21px}}
        @media(max-width:1100px){.pumk-report-header{grid-template-columns:160px 1fr 130px}.pumk-toolbar{grid-template-columns:1fr 1fr 1fr}.pumk-total-card{grid-row:1}.pumk-primary-grid{grid-template-columns:1fr 1fr}.pumk-primary-grid .pumk-card:first-child{grid-column:1/-1}.pumk-secondary-grid{grid-template-columns:1fr}.pumk-live-summary{grid-template-columns:1fr 1fr}.pumk-bri-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.pumk-bri-primary{grid-template-columns:1fr 1fr}.pumk-bri-primary .pumk-bri-card:first-child{grid-column:1/-1}.pumk-bri-lower,.pumk-bri-data-grid{grid-template-columns:1fr}.faq-heading{font-size:36px}}
        @media(max-width:720px){.tjsl-report-section{padding:28px 0}.tjsl-report-frame{border-width:1px;padding:14px 12px}.report-header{grid-template-columns:1fr 1fr}.report-title{grid-column:1/-1;grid-row:1;margin-bottom:8px}.report-logo.danantara{height:42px}.report-logo.inka{height:37px}.report-filters{grid-template-columns:1fr 1fr}.report-grid{grid-template-columns:1fr;grid-template-areas:"summary" "gauge" "pillar" "tpb" "priority" "featured" "regions"}.report-regions-content{grid-template-columns:1fr;height:auto}.region-map{height:280px}.report-table{font-size:8px}.report-card{padding:8px}.pumk-section{padding-bottom:36px}.pumk-heading{font-size:27px}.pumk-report-frame{border-width:1px;padding:14px 12px}.pumk-report-header{grid-template-columns:1fr 1fr}.pumk-report-title{grid-column:1/-1;grid-row:1;font-size:18px}.pumk-toolbar,.pumk-primary-grid,.pumk-secondary-grid,.pumk-live-summary,.pumk-bri-summary,.pumk-bri-primary{grid-template-columns:1fr}.pumk-primary-grid .pumk-card:first-child,.pumk-bri-primary .pumk-bri-card:first-child{grid-column:auto}.pumk-bri-filter-bar{justify-content:stretch}.pumk-year-form{width:100%;justify-content:space-between}.pumk-year-select{flex:1}.pumk-chart,.pumk-wide-chart,.pumk-bri-chart{height:230px}.pumk-bri-map{height:280px}.faq-section{padding:26px 0 38px}.faq-heading{margin-bottom:24px;font-size:28px}}
        .report-grid{grid-template-areas:"summary pillar tpb" "gauge pillar tpb" "priority priority regions"}
        .report-priority-card .report-chart{height:270px}
        .region-chart{position:relative;min-width:0;height:270px}
        @media(max-width:1100px){.report-grid{grid-template-areas:"summary summary" "gauge pillar" "tpb tpb" "priority priority" "regions regions"}}
        @media(max-width:720px){.report-grid{grid-template-areas:"summary" "gauge" "pillar" "tpb" "priority" "regions"}.region-chart{height:260px}}
        @media print{body>nav,.tjsl-report-section~section,footer{display:none!important}.tjsl-report-section{padding:0;background:#fff}.tjsl-report-frame{border:1px solid #111}.container-site{max-width:none!important;padding:0!important}}
