<style>
    .pumk-page-header{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:24px}.pumk-page-header-actions{display:flex;gap:10px;flex-wrap:wrap}
    .pumk-filter{display:grid;grid-template-columns:minmax(220px,2fr) repeat(3,minmax(150px,1fr)) auto auto;gap:10px;margin-bottom:20px;padding:16px}.pumk-field{display:flex;flex-direction:column;gap:6px}.pumk-field label{font-size:13px;font-weight:600}.pumk-input,.pumk-select,.pumk-textarea{width:100%;border:1px solid #d6d9df;border-radius:7px;background:#efefef;color:#0f172a;font:400 14px Poppins,sans-serif;outline:none;transition:border-color .15s,box-shadow .15s}.pumk-input,.pumk-select{height:43px;padding:0 13px}.pumk-textarea{min-height:100px;padding:12px 13px;resize:vertical}.pumk-input:focus,.pumk-select:focus,.pumk-textarea:focus{border-color:#2653ff;box-shadow:0 0 0 3px rgba(38,83,255,.12);background:#fff}.pumk-field-error{color:#dc2626;font-size:12px}
    .pumk-table-wrap{overflow-x:auto}.pumk-table{width:100%;border-collapse:collapse;font-size:13px}.pumk-table th{background:#0f1a34;color:#fff;font-weight:600;text-align:left}.pumk-table th,.pumk-table td{padding:13px 14px;border-bottom:1px solid #d8dce4;vertical-align:middle}.pumk-table tbody tr:hover{background:#f8fafc}.pumk-table td.actions{white-space:nowrap}.pumk-table-action{display:inline-flex;align-items:center;border:1px solid #cbd5e1;border-radius:6px;padding:6px 10px;color:#0f172a;font-size:12px;font-weight:600;text-decoration:none}.pumk-table-action:hover{background:#eef2ff;border-color:#2653ff;color:#163ed8}
    .pumk-badge{display:inline-flex;min-height:25px;align-items:center;border-radius:999px;padding:4px 9px;color:#fff;font-size:11px;font-weight:700;white-space:nowrap}.pumk-badge.lancar{background:#16a34a}.pumk-badge.kurang_lancar{background:#eab308;color:#422006}.pumk-badge.diragukan{background:#f97316}.pumk-badge.macet{background:#dc2626}.pumk-badge.belum{background:#64748b}
    .pumk-pagination{padding:16px}.pumk-pagination nav{display:flex;justify-content:center}.pumk-section{margin-top:20px;padding:10px 12px;box-shadow:0 3px 4px rgba(0,0,0,.24)}.pumk-section-title{margin:0 0 8px;font-size:20px;font-weight:700}.pumk-form-grid{display:block}.pumk-form-grid>.pumk-field{display:grid;grid-template-columns:250px minmax(0,1fr);align-items:start;gap:12px;padding:10px 0}.pumk-form-grid>.pumk-field>label:not(.pumk-checkbox-row){padding-top:11px}.pumk-form-grid>.pumk-field>.pumk-field-error{grid-column:2}.pumk-form-grid>.pumk-field>.pumk-checkbox-row{grid-column:2}.pumk-form-actions{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:20px;margin-top:28px}.pumk-checkbox-row{display:flex;align-items:center;gap:9px;min-height:43px}.pumk-checkbox-row input{width:18px;height:18px;accent-color:#2653ff}
    .pumk-data-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.pumk-data-item{min-height:82px;border:1px solid #e2e8f0;border-radius:8px;background:#fafafa;padding:13px}.pumk-data-item span{display:block;color:#64748b;font-size:11px}.pumk-data-item strong{display:block;margin-top:7px;font-size:14px;overflow-wrap:anywhere}.pumk-finance-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.pumk-finance-card{border-radius:9px;background:#fff;padding:18px;box-shadow:0 3px 5px rgba(0,0,0,.13)}.pumk-finance-card span{display:block;color:#64748b;font-size:11px}.pumk-finance-card strong{display:block;margin-top:8px;color:#0f172a;font-size:20px}.pumk-note{margin-top:14px;border-left:4px solid #eab308;background:#fefce8;padding:11px 13px;color:#713f12;font-size:12px;line-height:1.6}
    @media(max-width:1100px){.pumk-filter{grid-template-columns:repeat(2,minmax(0,1fr))}.pumk-finance-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.pumk-page-header{flex-direction:column}.pumk-page-header-actions{width:100%}.pumk-page-header-actions a{flex:1}.pumk-filter,.pumk-data-grid,.pumk-finance-grid{grid-template-columns:1fr}.pumk-form-grid>.pumk-field{grid-template-columns:1fr;gap:6px}.pumk-form-grid>.pumk-field>label:not(.pumk-checkbox-row){padding-top:0}.pumk-form-grid>.pumk-field>.pumk-field-error,.pumk-form-grid>.pumk-field>.pumk-checkbox-row{grid-column:1}.pumk-form-actions{grid-template-columns:1fr}.pumk-form-actions a,.pumk-form-actions button{width:100%}}
</style>
